/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_jniexamples_FieldAccess */

#ifndef _Included_com_marakana_jniexamples_FieldAccess
#define _Included_com_marakana_jniexamples_FieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_jniexamples_FieldAccess
 * Method:    accessFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_jniexamples_FieldAccess_accessFields
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
