/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FieldAccess */

#ifndef _Included_FieldAccess
#define _Included_FieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FieldAccess
 * Method:    accessFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FieldAccess_accessFields
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
